### PR TITLE
use lslint binaries from LSL package if installed

### PR DESCRIPTION
**Pull request by buildersbrewery**
# Status of pull request

This pull request has:

* [x] been tested
* [ ] not been tested

with this setup

* Operating system: `Win10 Pro x64 1703`
* Sublime Text Build `3131` on branch `dev`
* lslint version `0.4.3-xh` from `makopo/lslint`
* SublimeLinter version `v3.8.0+1`
* SublimeLinter-contrib-lslint version `v1.3.1`

### CODE REVIEW

**Comment by buildersbrewery** [comment]
compare <http://www.sublimelinter.com/en/latest/linter_methods.html?highlight=which#which>

**Comment by buildersbrewery** [comment]
@XenHat Too lazy to fix the docstrings now, either do it yourself or wait until tomorrow...

**Comment by XenHat** [comment]
image
👌

**Comment by XenHat** [comment]
Feel free to submit docstring fix at your convenience.

**Comment by buildersbrewery** [comment]
⚠️ Also... the "linter executable" section in the README should maybe mention the changes here. Will do that if not done by tomorrow.

**Comment by XenHat** [comment]
I added a somewhat smarter logic on ef3a139cc887b9428dfe7c9b477601aee7f7a4b8

**Comment by XenHat** [comment]
@buildersbrewery During the development of these fixes (see 78c42472fb39034bc34a9298a1dce84f250c0239), I had to delete the modified copy of my plugin contained in your package. Would it be possible to convert this copy into a dependency? This should be mostly safe now.

**Comment by buildersbrewery** [comment]
I'm not sure how to best answer your last post, but here goes:

* Keep in mind that this package would still depend upon SublimeLinter itself, though.
  * SublimeLinter is a Sublime Text 3 Package. makopo's package currently targets Sublime Text 2.
  * SublimeLinter is **NOT** a dependency package and not to be used that way as far as I understand it.
    * What you can do is add an installer reminder as discussed above.
* You could make this package a dependency, yes.
  * Dependency packages usually include binary files as per definition.
    * They are usually stand-alone packages.
    * They are completely different from SublimeLinter contributions.
    * You'd need to change the structure of this package according to <https://packagecontrol.io/docs/dependencies>. Dependency package structures are **very strict**, in contrast to other packages.

**Comment by XenHat** [comment]
I created this linter to make it easy for "everyone" (new scripters, and existing ones) to set up a LSL developing environment within sublime text. While I want to support your LSL package as much as possible, I heavily favor a drop-in solution without having to install 8 things, copy 3, etc etc.

I'm still trying to figure out what is possible, and what I can do to be as close as a one-click install as possible.

EDIT: In other words, I would like to collaborate toward making the installation as streamlined as possible without having to deal with manual fixing. I had to delete the linter python script in BB's LSL package in order to work on mine, which is installed using package control. Can we figure a way to not make this a problem for every user?

**Pull request merged**
