### PR TITLE
Update README, add github related files, remove language files

### PR DESCRIPTION
**Pull request by buildersbrewery**
See commits for details.

### CODE REVIEW

**Comment by buildersbrewery** [comment]
- I suggest using the [squash merge](https://help.github.com/articles/about-pull-request-merge-squashing) functionality built into GitHub, should you be interested in merging. Otherwise feel free to simply close the PR, cool with me.

squash merge

**Comment by XenHat** [comment]
Great work! I'm not the best at documenting for end-users. Thanks a bunch!

**Comment by buildersbrewery** [comment]
FYI: You'll still have to tag and release yourself.

**Comment by XenHat** [comment]
yes, I am aware. :)

**Pull request merged**
